version: 2
jobs:
  build:
    macos:
      xcode: "10.2.1"
    steps:
      - run:
          name: Print test info
          command: |
            echo "Hello World - this is a test of the emergency alert system"
  
      - checkout
      - run:
          name: Install CocoaPods
          command: | 
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install 
      - run:
          name: XcodeBuild
          command: | 
            xcodebuild -workspace BubbleTea.xcworkspace  -scheme BubbleTea_release  
                 -configuration Release archive -archivePath ./build/BubbleTea.xcarchive
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
